%% 通用函数2
function int_class = function_2(conf_begin_offset, conf_over_offset, ...
    conf_initial, conf_modifier, conf_noise, ...
    conf_stu, conf_begin_1_len, conf_begin_2_len, conf_begin_bias, ...
    conf_over_1_len, conf_over_2_len, conf_over_bias, conf_file)
    
end